//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazılımMuhendisligi
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int id { get; set; }
        public string companyName { get; set; }
        public double price { get; set; }
        public string customerName { get; set; }
        public string customerPhoneNumber { get; set; }
        public double point { get; set; }
        public string type { get; set; }
    }
}
