//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazılımMuhendisligi
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaign
    {
        public string TravelCompany_name { get; set; }
        public string originCity { get; set; }
        public string destinationCity { get; set; }
        public System.DateTime date { get; set; }
        public string estimatedTimeOfArrival { get; set; }
        public int capacity { get; set; }
        public double price { get; set; }
        public int campaignID { get; set; }
    }
}
