//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazılımMuhendisligi
{
    using System;
    using System.Collections.Generic;
    
    public partial class transportationservice
    {
        public int Bill_id { get; set; }
        public int Campaign_campaignID { get; set; }
        public int transportationID { get; set; }
    }
}
