//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazılımMuhendisligi
{
    using System;
    using System.Collections.Generic;
    
    public partial class travelcompany
    {
        public string name { get; set; }
        public double pointCoefficient { get; set; }
    }
}
