//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazılımMuhendisligi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uygarEntities1 : DbContext
    {
        public uygarEntities1()
            : base("name=uygarEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bill> bill { get; set; }
        public virtual DbSet<campaign> campaign { get; set; }
        public virtual DbSet<hotel> hotel { get; set; }
        public virtual DbSet<hotelreservation> hotelreservation { get; set; }
        public virtual DbSet<location> location { get; set; }
        public virtual DbSet<session> session { get; set; }
        public virtual DbSet<transportationservice> transportationservice { get; set; }
        public virtual DbSet<travelcompany> travelcompany { get; set; }
        public virtual DbSet<uuser> uuser { get; set; }
    }
}
